import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import { Navbar, Header, About, Contact1, Contact2, Cta, Locations, Packages, Services, Gallery } from '../components'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <Header />
        <Packages />
        <Services />
        <Contact1 />
        <About />
        <Cta />
        <Locations />
        <Gallery />
        <Contact2 />
      </main>
    </>
  )
}
